version: '3'
services:
  vf-proxy-api:
    build: .
    restart: unless-stopped
    image: 'vf-proxy-api'
    container_name: 'vf-proxy-api'
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
